i_name: "kush"
key: "newkey"
i_type: "t2.micro"
img: 'ami-08f63db601b82ff5f'
subnet: 'subnet-3bb8bd53'
sg: 'sg-01a26d3db794b83f8'
counts: 4 
zone: 'ap-south-1'

inventory: "/home/ec2-user/inventory.txt"
use_case: "webserver"
tag: "unique"                # required
