- hosts: "{{ host }}"
  vars_prompt:
          - name: host
            private: no
            prompt: " Enter host : " 
          - name: server_root
            private: no
            prompt: " Enter Document Root Directory : " 

          - name: port
            private: no
            prompt: " Enter Desired Port : " 
  tasks:
          - package:
                  name: "httpd"
                  state: present
          - name: "Custum Directory Root"
            file:
                  state: directory
                  path: "{{ server_root }}"
          - template : 
                  dest: "/etc/httpd/conf.d/custom.conf"
                  src: "setting.conf"
            notify: "restart httpd"
          - copy:
                  dest: "{{ server_root }}/index.html"
                  content: "Hi from kush"
          - service:
                  name: "httpd"
                  state: started
                  enabled: yes
  handlers:
          - name: "restart httpd"
            service:
                    name: "httpd"
                    state: reloaded

