- hosts: "{{ host }}"
  vars_prompt:
          - name: host
            private: no
            prompt: " Enter host " 
          - name: server_root
            private: no
            prompt: " Enter Document Root Directory" 

          - name: port
            private: no
            prompt: " Enter Assigned Port" 
  tasks:
          - package:
                  name: "httpd"
                  state: absent
          - file:
                  path: "/etc/httpd"
                  state: absent
          - file:
                  path: "{{ server_root }}"
                  state: absent

