- hosts: 52.66.69.185
  vars_prompt:
          - name: server_root
            private: no
            prompt: " Enter Document Root Directory : " 

          - name: port
            private: no
            prompt: " Enter Assigned Port : " 
  tasks:
          - package:
                  name: "httpd"
                  state: absent
          - file:
                  path: "/etc/httpd"
                  state: absent
          - file:
                  path: "{{ server_root }}"
                  state: absent
          - firewalld:
                   port: "{{ port }}/tcp"
                   state: disabled
                   permanent: yes
                   immediate: yes

