---
- name: "Create Aws Instance"
  hosts: localhost
  become: yes
  become_user: root 
  vars_files:
          - ~/secret.yml
          - type/default.yml
  vars:
                  ansible_python_interpreter: /usr/bin/python
  tasks:
          - name: " Deleting instance"
            ec2_instance:
                    state: absent
                    key_name: "{{ key }}"
                    tags:
                            tag: "{{ tag }}"
                    security_group: "{{ sg }}"
                    vpc_subnet_id: "{{ subnet }}"
                    region: "{{ zone }}"
                    aws_access_key: "{{ pass }}"
                    aws_secret_key: "{{ secret_pass }}"
          
          - name: "Deleting ip"
            lineinfile:
                  dest: "{{ inventory }}"
                  regexp: "#{{ tag }}"
                  line: "#{{ tag }}"
                  state: absent

          - meta: refresh_inventory 
