- hosts: test
  vars_prompt:
          - name: image
            prompt: "Enter Image with tag (e.g : centos:latest ) "
            private: no
          - name: name
            prompt: "Enter Container Image (e.g : Webserver ) "
            private: no
          - name: port
            prompt: "Enter port no. (e.g : 5050 ) "
            private: no
  tasks:
  tasks:
          - name: " Docker Installation"
            package:
                  name: "docker"
                  state: present
          - name: "Docker Service Start and Enabled"
            service:
                  name: "docker"
                  state: started 
                  enabled: yes
          - name: "Python and pip Installed"
            package:
                  name: 
                     - "python"
                     - "python2-pip"
                  state: present
          - name: "Docker  pip lib installation"
            pip:
                  name: docker
          - name: "Pull {{ image }} image "
            docker_image:
                    name: "{{ image }}"
                    source: pull
          - name: "Create volume Website "
            file:
                    state: "directory"
                    path: "/website"
          - name: "Website Webpage sent to volume"
            copy:
                  dest: "/website/index.php"
                  content: >
                          "<pre>
                          <?php

                          print `ifconfig`

                          ?>
                          <\pre>"      
          - name: "Launch Container {{ name }} "
            community.general.docker_container:
                    name: "{{ name }}"
                    image: "{{ image }}"
                    ports: "{{ port }}:80"
                    volumes: "/website/:/usr/local/apache2/htdocs/" 
