- hosts: test
  vars_prompt:
          - name: image
            prompt: "Enter Image with tag (e.g : centos:latest ) "
            private: no
          - name: name
            prompt: "Enter Container Image (e.g : Webserver ) "
            private: no
  tasks:
          - name: " Docker Installation"
            package:
                  name: "docker"
                  state: present
          - name: "Docker Service Start and Enabled"
            service:
                  name: "docker"
                  state: started 
                  enabled: yes
          - name: "Pull {{ image }} image "
            docker_container:
                    name: "{{ name }}"
                    image: "{{ image }}"
                    ports: "9090:80"
                    state: present
          - docker_container:
                  name: "{{ name }}"
                  image: "{{ image }}"
                  state: started
          


