- name: "Pre-Installtion Downloading"
  hosts: localhost
  # become: yes
  #become_user: root
  vars:
          - ansible_python_interpreter: /usr/bin/python
          - file_id: 17UWQNVdBdGlyualwWX4Cc96KyZhD-lxz
  tasks:
          - name: "Java File Downloading steps"
            block:
                  - shell: "ls jdk-8u171-linux-x64.rpm"
                    changed_when: false 
            rescue:
                   - package:
                             name:
                                    - "python3"
                                    - "python2-pip"

                   - pip:
                       name: gdown
                   - shell: "gdown --id {{ file_id }}"

- name: "Configuring Datanode"
  hosts: datanode
  vars:
          dir: /hadoop_datanode
          node: data
          ip: "{{ groups['namenode'][0] }}"
          port: 9001
  tasks:
          - name: "Copy Installing file"
            copy:
                    src: "{{ item }}"
                    dest: "/root"

            loop:
                            - "hadoop-1.2.1-1.x86_64.rpm"
                            - "jdk-8u171-linux-x64.rpm"
                    
          - name: "Installing Java"
            package:
                    name: "jdk-8u171-linux-x64.rpm"
                    state: present
          - name: "Checking hadoop and installing"
            block:
                    - name: "Checking hadoop"
                      command: "rpm -q hadoop"
                      changed_when: False
            rescue:
                    - name: "Installing hadoop"
                      command: "rpm -i hadoop-1.2.1-1.x86_64.rpm --force"
          - name: "Configuring Hadoop Datanode"
            template:
                    src: "{{ item }}"
                    dest: "/etc/hadoop"

            loop:
                            - "hdfs-site.xml"
                            - "core-site.xml"
            notify:
                    - "Creating Datanode Directory"
                    - "start hadoop"

  handlers:
          - name: "Creating Datanode Directory"
            file:
                    path: "{{ dir }}"
                    state: "directory"
          - name: "start hadoop"
            command: "hadoop-daemon.sh start datanode"

