- name: "Deleting Namenode"
  hosts: namenode
  vars:
          dir: /hadoop_namenode

  tasks:
          - name: "stop hadoop"
            command: "hadoop-daemon.sh stop namenode"
            ignore_errors: yes
          - name: "Uninstalling packages"
            package:
                    name: 
                     - java
                     - hadoop
                    state: absent
          - name: "Deleting Namenode Directory"
            file:
                    path: "{{ item }}"
                    state: "absent"
            loop:
                    - "{{ dir }}"
                    - "/etc/hadoop"

